### ISSUE TITLE
Remove `export *`

### ISSUE THREAD

**Issue by grant** [cloudevents/sdk-javascript#272]
## Expected

`export *` is seen in a few files. This is usually a bad practice because we can't see what we export and we can't click to definition.

Just `export` the class/const with the definition.

## Actual

A few files have unnecessary `export * ` patterns.

**Comment by grant** [comment]
Specifically here:

https://github.com/cloudevents/sdk-javascript/blob/3d82fb629182edaee11e571ea895a5f8a7456a0e/src/transport/index.ts

It's actually causing issues with my build for some reason:

```
node_modules/cloudevents/dist/transport/index.d.ts:3:10 - error TS1005: 'from' expected.

3 export * as http from "./http/headers";
           ~~

node_modules/cloudevents/dist/transport/index.d.ts:3:10 - error TS1141: String literal expected.

3 export * as http from "./http/headers";
           ~~

node_modules/cloudevents/dist/transport/index.d.ts:3:13 - error TS1005: ';' expected.

3 export * as http from "./http/headers";
              ~~~~

node_modules/cloudevents/dist/transport/index.d.ts:3:13 - error TS2304: Cannot find name 'http'.

3 export * as http from "./http/headers";
              ~~~~

node_modules/cloudevents/dist/transport/index.d.ts:3:18 - error TS1005: ';' expected.

3 export * as http from "./http/headers";
                   ~~~~

node_modules/cloudevents/dist/transport/index.d.ts:3:18 - error TS2304: Cannot find name 'from'.

3 export * as http from "./http/headers";
                   ~~~~

node_modules/cloudevents/dist/transport/index.d.ts:3:23 - error TS1005: ';' expected.

3 export * as http from "./http/headers";
                        ~~~~~~~~~~~~~~~~
```
